version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
    container_name: elasticsearch
    environment:
      - ELASTIC_PASSWORD=SuperSecret
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: https://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: SuperSecret
    depends_on:
      - elasticsearch
    networks:
      - elastic

  # Service to build and run your Rust application
  elasticsearch-learning:
    build: .  # Build from the current directory (where your Dockerfile is)
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data  # Optional: Mount a local directory for persistent data
    networks:
      - elastic

volumes:
  esdata:

networks:
  elastic:
    driver: bridge

