name: Build for the first time

on: [push]  # Trigger on push events

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - uses: actions/checkout@v3  # Checkout the repository code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run containers
        run: |
          docker-compose build
          docker-compose up -d

      - name: Tear down containers
        run: docker-compose down

